import { test, expect } from '@playwright/test';
test('guarda, refresca el avance, edita y maneja errores sin perder datos', async ({ page }) => {
  const missions = [{ misionId: 1, nombre: 'Lectura', descripcion: 'Leer un capítulo' }, { misionId: 2, nombre: 'Práctica', descripcion: null }];
  let students: unknown[] = [];
  let conflict = false;
  let refreshFails = false;
  await page.route('**/api/misiones', route => route.fulfill({ json: missions }));
  await page.route('**/api/estudiantes', route => route.fulfill(refreshFails ? { status: 500, json: { error: 'Error' } } : { json: students }));
  await page.route('**/api/registro', async route => {
    if (conflict) return route.fulfill({ status: 409, json: { error: 'El correo ya pertenece a otro estudiante.' } });
    const body = route.request().postDataJSON();
    expect(body.estudiante.carnet).toBe('UI-001');
    expect(body.misiones).toEqual([{ misionId: 1, estado: true }, { misionId: 2, estado: false }]);
    students = [{ ...body.estudiante, misiones: body.misiones }];
    await route.fulfill({ json: { mensaje: 'Guardado' } });
  });
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Guardar estudiante' })).toBeEnabled();
  await page.getByLabel('Carnet', { exact: true }).fill('UI-001');
  await page.getByLabel('Nombre completo').fill('Ana Prueba');
  await page.getByLabel('Correo electrónico').fill('ana@example.com');
  await page.getByRole('checkbox', { name: /Lectura/ }).check();
  await page.getByRole('button', { name: 'Guardar estudiante' }).click();
  await expect(page.getByRole('status')).toHaveText('Registro guardado correctamente.');
  await expect(page.getByRole('progressbar')).toHaveAttribute('value', '50');
  await page.getByRole('button', { name: 'Editar a Ana Prueba' }).click();
  await expect(page.getByLabel('Carnet', { exact: true })).toHaveAttribute('readonly', '');
  await expect(page.getByRole('checkbox', { name: /Lectura/ })).toBeChecked();
  conflict = true;
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(page.locator('main').getByRole('alert')).toContainText('El correo ya pertenece');
  await expect(page.getByLabel('Nombre completo')).toHaveValue('Ana Prueba');
  conflict = false; refreshFails = true;
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await expect(page.getByRole('status')).toContainText('El registro se guardó, pero');
  refreshFails = false;
  await page.getByRole('button', { name: 'Reintentar' }).click();
  await expect(page.locator('main').getByRole('alert')).toHaveCount(0);
  await page.screenshot({ path: 'test-results/tablero-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/tablero-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
test('permite recuperar una carga fallida y muestra catálogo vacío', async ({ page }) => {
  let failed = true;
  await page.route('**/api/misiones', route => route.fulfill(failed ? { status: 500, json: {} } : { json: [] }));
  await page.route('**/api/estudiantes', route => route.fulfill({ json: [] }));
  await page.goto('/');
  await expect(page.locator('main').getByRole('alert')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Guardar estudiante' })).toBeDisabled();
  failed = false;
  await page.getByRole('button', { name: 'Reintentar' }).click();
  await expect(page.getByText('No hay misiones disponibles.', { exact: false })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Guardar estudiante' })).toBeEnabled();
});
